### ISSUE TITLE
Ordering the bubbles

### ISSUE THREAD

**Issue by ghost** [jcheng5/bubbles#1]
Hi,

In bubbles.js replacing `.sort(null)` by `.sort( function(a, b) { return  -(a.value - b.value);} )` orders the bubbles from the center to the edge.
I am wondering how to include this as an option (e.g. order = TRUE). Then I guess it will be necessary to pass a list to htmlwidgets::createWidget. But how to retrieve the two elements in the JS function (the data frame currently returned and the order TRUE/FALSE value)?

Thank you!

**Comment by jcheng5** [comment]
Is there a reason you can't just sort the data before you pass it to bubbles?
